### ISSUE TITLE
Opa, o chat está muito massa!

### ISSUE THREAD

**Issue by BrunoFDeveloper** [PaulaoDev/KhanChat#1]
Achei um bug no chat, queria poder ajudar, porém o código não minificado não está no projeto, fazendo com que dê erro até mesmo no uso local!
<img width="504" alt="screen shot 2017-12-19 at 9 48 53" src="https://user-images.githubusercontent.com/4235143/34155782-dbb9a550-e4a1-11e7-84da-560700ebd0da.png">

**Comment by PaulaoDev** [comment]
A sim esqueci de remover o webpack no npm start
